name: demo
on:
  push:
    branches:
      - '*'
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 17
      - name: Build with Maven
        run: ./mvnw clean package
      - name: Log into OCIR
        run: |
          echo "${{ secrets.OCI_AUTH_TOKEN }}" | docker login eu-frankfurt-1.ocir.io -u "frur454twuum/tjaksic22" --password-stdin
      - name: Docker Build
        run: |
          docker build -t eu-frankfurt-1.ocir.io/frur454twuum/kolokvij/hello-world-app:latest .
      - name: Docker Push
        run: |
          docker push eu-frankfurt-1.ocir.io/frur454twuum/kolokvij/hello-world-app:latest
  deploy-job:
    name: Deploy Job
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.5.0
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}
      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s-deployment.yaml
